<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>小猪钱吧</title>
    <meta name="description" content="“小猪钱吧”是一个能帮你用手机赚零花钱的小助手，按照引导完成任务，得到奖励即可提现。">
    <meta name="keywords" content="手机赚钱 好友分享 任务 零花钱">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <link rel="apple-touch-icon-precomposed" href="https://qianba.1024.pm/uploads/apple-touch-icon-114x114-2.png">
    <link rel="shortcut icon" href="https://qianba.1024.pm/uploads/favicon.ico">
    <style type="text/css">
    	* {
    		padding: 0;
    		margin: 0;
    	}
    	body {
    		//padding: 0 0 30px;
    		font-size: 16px;
    	}
    	.pd-lr {
    		padding: 0 15px;
    	}
    	.cn_split {
    		//border-bottom: 4px solid #eee;
    	}
    	.head {
    		margin: 0 15px;
    		font-size: 22px;
    		font-weight: 800;
    		line-height: 40px;
    		text-align: center;
    	}
    	.title {
    		padding: 5px 0;
    	}
    	.des {
    		padding: 20px 15px;
    		font-size: 16px;
    		line-height: 1.6;
    	}
        .code {
            display: block;
            text-align: center;
            font-size: 24px;
            color: orange;
        }
    	.share {
    		display: block;
    		width: 100%;
    		height: auto;
    	}
    	.footer {
    		margin-top: 30px;
    		padding: 20px 15px;
    		color: #fff;
    		background-color: #3e4245;
    	}
    	.footer .item,.footer .link {
    		line-height: 30px;
    		//padding: 0 15px;
    		margin-right: 10px;
    		font-size: 14px;
    		color: #fff;
    	}
    	.footer .link:visited {
    		color: #fff;
    	}
    </style>
</head>
<body>
	<h1 class="head cn_split">
		<header class="title">小猪钱吧</header>
	</h1>
	<div class="des pd-lr">
		“小猪钱吧”是一个能帮你用手机赚零花钱的小助手，按照引导完成任务，得到奖励即可提现。
	</div>
    <?php if ($code) {?>
    <span class="code">邀请码: <?php echo $code;?></span>
    <?php }?>

	<img class="share" src="https://qianba.1024.pm/uploads/qianba.jpeg"></img>

	<div class="footer">
		<span class="item">友情链接：</span>
		<a class="link" href="http://www.startwz.com/">网赚导航</a>
	</div>
</body>
</html>

